// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20210119233048_addReviews")]
    partial class addReviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Travel.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "London",
                            Country = "England"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Amsterdam",
                            Country = "Netherlands"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Berlin",
                            Country = "Germany"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "South Pole",
                            Country = "Antartica"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Kyoto",
                            Country = "Japan"
                        },
                        new
                        {
                            DestinationId = 6,
                            City = "New York City",
                            Country = "USA"
                        },
                        new
                        {
                            DestinationId = 7,
                            City = "Ho Chi Minh",
                            Country = "Vietnam"
                        });
                });

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<int>("DestinationId");

                    b.Property<int>("Rating");

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.HasOne("Travel.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
